#ifndef SOLUTION_HPP
#define SOLUTION_HPP

// Do not edit this file!

// Implement the following functions:

int Obfuscate(int input, int iter);
char Obfuscate(char input, int iter);

void EncryptCreditCard(unsigned long long card_number);

#endif
